package rules

// atomSchema holds expected input variable names and output names for an atom resource type.
// Generated by scripts/scaffold-atom.py. Regenerate after major AWS provider version bumps.
type atomSchema struct {
	inputs  []string
	outputs []string
}

// resourceSchemas maps resource types to expected atom inputs and outputs.
var resourceSchemas = map[string]atomSchema{
	"aws_s3_bucket_versioning": {
		inputs:  []string{"bucket", "expected_bucket_owner", "mfa", "region", "versioning_configuration"},
		outputs: []string{"bucket", "id", "mfa", "region", "versioning_configuration"},
	},
	"aws_s3_bucket": {
		inputs:  []string{"bucket", "bucket_namespace", "bucket_prefix", "force_destroy", "object_lock_enabled", "region", "tags", "timeouts"},
		outputs: []string{"arn", "bucket", "bucket_domain_name", "bucket_namespace", "bucket_prefix", "bucket_region", "bucket_regional_domain_name", "force_destroy", "hosted_zone_id", "id", "object_lock_enabled", "region", "tags", "tags_all", "website_domain", "website_endpoint"},
	},
	"aws_s3_bucket_public_access_block": {
		inputs:  []string{"block_public_acls", "block_public_policy", "bucket", "ignore_public_acls", "region", "restrict_public_buckets", "skip_destroy"},
		outputs: []string{"block_public_acls", "block_public_policy", "bucket", "id", "ignore_public_acls", "region", "restrict_public_buckets", "skip_destroy"},
	},
	"aws_s3_bucket_policy": {
		inputs:  []string{"bucket", "policy", "region"},
		outputs: []string{"bucket", "id", "policy", "region"},
	},
	"aws_s3_bucket_ownership_controls": {
		inputs:  []string{"bucket", "region", "rule"},
		outputs: []string{"bucket", "id", "region", "rule"},
	},
	"aws_s3_bucket_server_side_encryption_configuration": {
		inputs:  []string{"bucket", "expected_bucket_owner", "region", "rule"},
		outputs: []string{"bucket", "id", "region", "rule"},
	},
	"aws_s3_bucket_logging": {
		inputs:  []string{"bucket", "expected_bucket_owner", "region", "target_bucket", "target_object_key_format", "target_prefix"},
		outputs: []string{"bucket", "id", "region", "target_bucket", "target_object_key_format", "target_prefix"},
	},
	"aws_s3_bucket_lifecycle_configuration": {
		inputs:  []string{"bucket", "expected_bucket_owner", "region", "rule", "timeouts", "transition_default_minimum_object_size"},
		outputs: []string{"bucket", "expected_bucket_owner", "id", "region", "rule", "transition_default_minimum_object_size"},
	},
	"aws_s3_bucket_object_lock_configuration": {
		inputs:  []string{"bucket", "expected_bucket_owner", "rule"},
		outputs: []string{"bucket", "expected_bucket_owner", "id"},
	},
	"aws_s3_bucket_cors_configuration": {
		inputs:  []string{"bucket", "cors_rule", "expected_bucket_owner"},
		outputs: []string{"bucket", "expected_bucket_owner", "id"},
	},
	"aws_s3_bucket_website_configuration": {
		inputs:  []string{"bucket", "error_document", "expected_bucket_owner", "index_document", "redirect_all_requests_to", "region", "routing_rule"},
		outputs: []string{"bucket", "error_document", "expected_bucket_owner", "id", "index_document", "redirect_all_requests_to", "region", "routing_rule", "website_domain", "website_endpoint"},
	},
	"aws_s3_bucket_notification": {
		inputs:  []string{"bucket", "eventbridge", "lambda_function", "queue", "topic"},
		outputs: []string{"bucket", "id"},
	},
	"aws_s3_bucket_replication_configuration": {
		inputs:  []string{"bucket", "role", "rule"},
		outputs: []string{"bucket", "id", "role"},
	},
	"aws_iam_role": {
		inputs:  []string{"assume_role_policy", "description", "force_detach_policies", "max_session_duration", "name", "name_prefix", "path", "permissions_boundary", "tags"},
		outputs: []string{"arn", "assume_role_policy", "create_date", "description", "force_detach_policies", "id", "max_session_duration", "name", "name_prefix", "path", "permissions_boundary", "tags", "tags_all", "unique_id"},
	},
	"aws_iam_role_policy": {
		inputs:  []string{"name", "name_prefix", "policy", "role"},
		outputs: []string{"id", "name", "name_prefix", "policy", "role"},
	},
	"aws_iam_role_policy_attachment": {
		inputs:  []string{"policy_arn", "role"},
		outputs: []string{"id", "policy_arn", "role"},
	},
	"aws_iam_user": {
		inputs:  []string{"force_destroy", "name", "path", "permissions_boundary", "tags"},
		outputs: []string{"arn", "force_destroy", "id", "name", "path", "permissions_boundary", "tags", "tags_all", "unique_id"},
	},
	"aws_iam_group": {
		inputs:  []string{"name", "path"},
		outputs: []string{"arn", "id", "name", "path", "unique_id"},
	},
	"aws_iam_policy": {
		inputs:  []string{"delay_after_policy_creation_in_ms", "description", "name", "name_prefix", "path", "policy", "tags"},
		outputs: []string{"arn", "attachment_count", "delay_after_policy_creation_in_ms", "description", "id", "name", "name_prefix", "path", "policy", "policy_id", "tags", "tags_all"},
	},
	"aws_iam_user_policy": {
		inputs:  []string{"name", "name_prefix", "policy", "user"},
		outputs: []string{"id", "name", "name_prefix", "policy", "user"},
	},
	"aws_iam_group_policy": {
		inputs:  []string{"group", "name", "name_prefix", "policy"},
		outputs: []string{"group", "id", "name", "name_prefix", "policy"},
	},
	"aws_iam_user_policy_attachment": {
		inputs:  []string{"policy_arn", "user"},
		outputs: []string{"id", "policy_arn", "user"},
	},
	"aws_iam_group_policy_attachment": {
		inputs:  []string{"group", "policy_arn"},
		outputs: []string{"group", "id", "policy_arn"},
	},
	"aws_iam_user_group_membership": {
		inputs:  []string{"groups", "user"},
		outputs: []string{"groups", "id", "user"},
	},
	"github_actions_organization_secret": {
		inputs:  []string{"encrypted_value", "plaintext_value", "secret_name", "visibility"},
		outputs: []string{"created_at", "id", "updated_at"},
	},
	"github_actions_organization_secret_repositories": {
		inputs:  []string{"secret_name", "selected_repository_ids"},
		outputs: []string{"id"},
	},
	"github_app_installation_repository": {
		inputs:  []string{"installation_id", "repository"},
		outputs: []string{"id", "repo_id"},
	},
	"aws_ecs_cluster": {
		inputs:  []string{"configuration", "name", "region", "service_connect_defaults", "setting", "tags"},
		outputs: []string{"arn", "configuration", "id", "name", "region", "service_connect_defaults", "setting", "tags", "tags_all"},
	},
	"aws_ecs_cluster_capacity_providers": {
		inputs:  []string{"capacity_providers", "cluster_name", "default_capacity_provider_strategy", "region"},
		outputs: []string{"capacity_providers", "cluster_name", "default_capacity_provider_strategy", "id", "region"},
	},
	"aws_ecs_task_definition": {
		inputs:  []string{"container_definitions", "cpu", "enable_fault_injection", "ephemeral_storage", "execution_role_arn", "family", "ipc_mode", "memory", "network_mode", "pid_mode", "placement_constraints", "proxy_configuration", "region", "requires_compatibilities", "runtime_platform", "skip_destroy", "tags", "task_role_arn", "track_latest", "volume"},
		outputs: []string{"arn", "arn_without_revision", "container_definitions", "cpu", "enable_fault_injection", "ephemeral_storage", "execution_role_arn", "family", "id", "ipc_mode", "memory", "network_mode", "pid_mode", "placement_constraints", "proxy_configuration", "region", "requires_compatibilities", "revision", "runtime_platform", "skip_destroy", "tags", "tags_all", "task_role_arn", "track_latest", "volume"},
	},
	"aws_eks_cluster": {
		inputs:  []string{"access_config", "bootstrap_self_managed_addons", "compute_config", "control_plane_scaling_config", "deletion_protection", "enabled_cluster_log_types", "encryption_config", "force_update_version", "kubernetes_network_config", "kubernetes_version", "name", "outpost_config", "region", "remote_network_config", "role_arn", "storage_config", "tags", "timeouts", "upgrade_policy", "vpc_config", "zonal_shift_config"},
		outputs: []string{"access_config", "arn", "bootstrap_self_managed_addons", "certificate_authority", "cluster_id", "compute_config", "control_plane_scaling_config", "created_at", "deletion_protection", "enabled_cluster_log_types", "encryption_config", "endpoint", "force_update_version", "id", "identity", "kubernetes_network_config", "name", "outpost_config", "platform_version", "region", "remote_network_config", "role_arn", "status", "storage_config", "tags", "tags_all", "timeouts", "upgrade_policy", "version", "vpc_config", "zonal_shift_config"},
	},
	"aws_eks_node_group": {
		inputs:  []string{"ami_type", "capacity_type", "cluster_name", "disk_size", "force_update_version", "instance_types", "kubernetes_version", "labels", "launch_template", "node_group_name", "node_group_name_prefix", "node_repair_config", "node_role_arn", "region", "release_version", "remote_access", "scaling_config", "subnet_ids", "tags", "taint", "timeouts", "update_config", "warm_pool_config"},
		outputs: []string{"ami_type", "arn", "capacity_type", "cluster_name", "disk_size", "force_update_version", "id", "instance_types", "labels", "launch_template", "node_group_name", "node_group_name_prefix", "node_repair_config", "node_role_arn", "region", "release_version", "remote_access", "resources", "scaling_config", "status", "subnet_ids", "tags", "tags_all", "taint", "timeouts", "update_config", "version", "warm_pool_config"},
	},
	"aws_eks_addon": {
		inputs:  []string{"addon_name", "addon_version", "cluster_name", "configuration_values", "namespace_config", "pod_identity_association", "preserve", "region", "resolve_conflicts_on_create", "resolve_conflicts_on_update", "service_account_role_arn", "tags", "timeouts"},
		outputs: []string{"addon_name", "addon_version", "arn", "cluster_name", "configuration_values", "created_at", "id", "modified_at", "namespace_config", "pod_identity_association", "preserve", "region", "resolve_conflicts_on_create", "resolve_conflicts_on_update", "service_account_role_arn", "tags", "tags_all", "timeouts"},
	},
	"aws_eks_access_entry": {
		inputs:  []string{"cluster_name", "kubernetes_groups", "principal_arn", "region", "tags", "timeouts", "type", "user_name"},
		outputs: []string{"access_entry_arn", "cluster_name", "created_at", "id", "kubernetes_groups", "modified_at", "principal_arn", "region", "tags", "tags_all", "timeouts", "type", "user_name"},
	},
	"aws_iam_openid_connect_provider": {
		inputs:  []string{"client_id_list", "tags", "thumbprint_list", "url"},
		outputs: []string{"arn", "client_id_list", "id", "tags", "tags_all", "thumbprint_list", "url"},
	},
	"aws_launch_template": {
		inputs:  []string{"block_device_mappings", "capacity_reservation_specification", "cpu_options", "credit_specification", "default_version", "description", "disable_api_stop", "disable_api_termination", "ebs_optimized", "enclave_options", "hibernation_options", "iam_instance_profile", "image_id", "instance_initiated_shutdown_behavior", "instance_market_options", "instance_requirements", "instance_type", "kernel_id", "key_name", "license_specification", "maintenance_options", "metadata_options", "monitoring", "name", "name_prefix", "network_interfaces", "network_performance_options", "placement", "private_dns_name_options", "ram_disk_id", "region", "secondary_interfaces", "security_group_names", "tag_specifications", "tags", "update_default_version", "user_data", "vpc_security_group_ids"},
		outputs: []string{"arn", "block_device_mappings", "capacity_reservation_specification", "cpu_options", "credit_specification", "default_version", "description", "disable_api_stop", "disable_api_termination", "ebs_optimized", "enclave_options", "hibernation_options", "iam_instance_profile", "id", "image_id", "instance_initiated_shutdown_behavior", "instance_market_options", "instance_requirements", "instance_type", "kernel_id", "key_name", "latest_version", "license_specification", "maintenance_options", "metadata_options", "monitoring", "name", "name_prefix", "network_interfaces", "network_performance_options", "placement", "private_dns_name_options", "ram_disk_id", "region", "secondary_interfaces", "security_group_names", "tag_specifications", "tags", "tags_all", "update_default_version", "user_data", "vpc_security_group_ids"},
	},
}
