package rules

// atomSchema holds expected input variable names and output names for an atom resource type.
// Generated by scripts/scaffold-atom.py. Regenerate after major AWS provider version bumps.
type atomSchema struct {
	inputs  []string
	outputs []string
}

// resourceSchemas maps resource types to expected atom inputs and outputs.
var resourceSchemas = map[string]atomSchema{
	"aws_s3_bucket_versioning": {
		inputs:  []string{"bucket", "id", "mfa", "region", "versioning_configuration"},
		outputs: []string{"bucket", "id", "mfa", "region", "versioning_configuration"},
	},
}
